### ISSUE TITLE
Label row and column numbers on the grid

### ISSUE THREAD

**Issue by BetterToko** [MrMilliganGHS/TTT2022#24]
Right now the grid looks something like this
```
_ _ _ 
_ _ _ 
_ _ _ 
```
The players have to input row and column numbers to place an X or O. The problem is the user might not know what the row and column numbers are. The game could be improved by adding labels like this on the grid:
```
  0 1 2
0 _ _ _ 
1 _ _ _ 
2 _ _ _ 
```

**Comment by MrMilliganGHS** [comment]
Closed by #34
