### ISSUE TITLE
X's and O's can be overwritten

### ISSUE THREAD

**Issue by branhost** [MrMilliganGHS/TTT2022#6]
## Issue

An existing X or O can be overwritten by the other player during their turn.

## Steps to Reproduce
1. Start the game
2. Put an X anywhere on the board as player 1
3. Put an O in the same position as the X as player 2

## Example Output
```
_ _ _ 
_ _ _ 
_ _ _ 
Player 1
Which row would you like to choose? 0
Which row would you like to choose? 0
X _ _ 
_ _ _ 
_ _ _ 
Player 2
Which row would you like to choose? 0
Which row would you like to choose? 0
O _ _ 
_ _ _ 
_ _ _ 
```

## Possible Solution
Check if an X or O exists in the user's selected cell before placing an X or O in that cell.

**Comment by Rnguyen85th** [comment]
Issue has either been fixed before code was pulled and altered, or I am unable to recreate the bug. Can someone test out if this bug is still active? Hopefully not in the recent version.
